### ISSUE TITLE
Create rounded click here button

### ISSUE THREAD

**Issue by mtlaney** [mtlaney/finance_social#2]
## Notes
* Customer would like a fancy click here button *

## Acceptance Criteria
- [ ] Button is rounded
- [ ] Button is blue
- [ ] Button has a hover effed

## Tasks
- [ ] Mockup Approved
- [ ] PM approved

## Definition of Done
- [ ] Pull requests meet technical definition of done
- [ ] Compare finished design with mockup
- [ ] Usability tested

**Comment by mtlaney** [comment]
Working on this here bad boy @mtlaney
